### ISSUE TITLE
Define build script

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/ts-generator#4]
- [ ] run tests (deferred to #15)
- [x] lint (#8)
- [x] invoke TypeScript for type-checking (#11)
- [x] invoke Babel for compilation (#13)

Bonus: parallelize the first three?
